[WOR-1396] Always create a landing zone during these cloud context tests (#1547)
The DeleteAzureContextFlightTest test has been failing consistently the past few days. I am able to reproduce the issue locally as well:

bio.terra.landingzone.db.exception.LandingZoneNotFoundException: Landing Zone with billing profile 4a5afeaa-b3b2-fa51-8e4e-9dbf294b7837 not found.	
	at bio.terra.landingzone.db.LandingZoneDao.lambda$getLandingZoneByBillingProfileId$1(LandingZoneDao.java:181)	
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)	
	at bio.terra.landingzone.db.LandingZoneDao.getLandingZoneByBillingProfileId(LandingZoneDao.java:178)
My hunch is that these tests were only passing previously because they were running after another connected test had setup the landing zone. I've adjusted the test to always create a landing zone instead.