[WOR-1588] Spring Boot 3.2.3, k8s client 20.0.1, TCL 1.1.6, LZS 0.0.317 (#1686)
* [WOR-1566] Upgrade io.kubernetes:client-java to 20.0.1 (#1675)

* Remove unused DeleteInitialPods integration test

Along with its corresponding BasicResiliency test suite.

This tests the resiliency of Kubernetes and was added several years ago as an example, but hasn't been running since 2022.  Rather than clean up integration project dependencies to get it to compile, we decided to remove it.

* Adjust non-standard imports

E.g. we should use Apache Commons imports rather than Liquibase's repackaged versions.

The presence of more direct dependencies than are necessary makes it easier to accidentally add these nonstandard imports.

* Upgrade Spring Boot 3.2.3, TCL 1.1.1, LZS 0.0.314

TCL and LZS upgrades ensure that k8s client 20.0.1 is used consistently throughout.

Upgraded Spring Boot from 3.1.2 -> 3.2.3 and cleaned up unnecessary dependency definitions.  Moved Spring Boot conventions to their own file, to enforce Spring Boot dependency overrides consistently.

Dependency reorganization: Dependabot isn't updating dependencies that aren't at the root of their project's directory.  There is likely a better way to accomplish this and/or share dependency versions, but for now, pulling out service's dependencies to the root so that they're updated going forward (most critical).  This is the reason that we were seeing discrepancies in dependencies between service and integration… integration defines its deps at the root within its build file, so Dependabot was keeping it updated.

* Dependabot should update Spring Boot

We maximize our chances at keeping on top of vulnerable dependencies by using Spring Boot dependency manager and BOMs, minimizing superfluous dependency definitions and pins, and keeping all up to date via Dependabot.

So, let's tell Dependabot to stop ignoring Spring Boot updates.

* Forgot to commit the Spring Boot 3.1.2 -> 3.2.3 upgrade

* Update Azure, AWS dependencies

These dependencies were not getting picked up by Dependabot due to the directory structure.
Bringing them to latest to give us a head start.

* Use TCL 1.1.1's StairwayLoggingHook

Rather than defining our own as a Spring Component.

This eliminates duplicate code, and removes a potential source of autowiring issues due to bean name conflicts.

* Spotless

* Revert com.azure:azure-storage-blob upgrade

Dropped back down from 12.25.3 -> 12.21.1 because of failing unit test:

AsureStorageAccessServiceUnitTest.createAzureStorageContainerSasToken_computesAuthHash showed an unexpected auth hash.
'org.opentest4j.AssertionFailedError: expected: <CFB533C099640123124FA52E02EF82C97CD28CE7AD7ACF94532982569F98F920> but was: <19ABE52309A3733175CCBAD669CD895EED970910E1E8784A4CA09624E723220B>'

* Upgrade azure-storage-blob again

And update the expected SAS token SHA in unit test.

@aherbst-broad says:
'I think the sas token hash breakage is expected, the service version has changed from sv=2021-12-02 to sv=2023-11-03'

* Add SourceClear plug-in and instructions for running scans

* Update TCL 1.1.6, LZS 0.0.317

This version of TCL includes a fix to KubePodListener, and is back to k8s client 20.0.1.
This version of LZS is also on k8s client 20.0.1.

Tell Dependabot to ignore k8s client upgrades, due to intermingling of legacy and non-legacy versions.