Revert com.azure:azure-storage-blob upgrade
Dropped back down from 12.25.3 -> 12.21.1 because of failing unit test:

AsureStorageAccessServiceUnitTest.createAzureStorageContainerSasToken_computesAuthHash showed an unexpected auth hash.
'org.opentest4j.AssertionFailedError: expected: <CFB533C099640123124FA52E02EF82C97CD28CE7AD7ACF94532982569F98F920> but was: <19ABE52309A3733175CCBAD669CD895EED970910E1E8784A4CA09624E723220B>'