Roll back integration build changes to add spring boot and dependency management plug-ins
Integration test set-up was failing, it looks like there was a different version incompatibility that I suspect comes from the addition of those two plug-ins:

java.lang.NoSuchMethodError: 'java.lang.ClassLoader ch.qos.logback.core.util.Loader.systemClassloaderIfNull(java.lang.ClassLoader)'
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:73)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:66)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:52)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:196)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:183)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:486)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:472)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:421)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:447)
	at bio.terra.testrunner.runner.TestRunner.<clinit>(TestRunner.java:28)
	at bio.terra.testrunner.common.commands.RunTest.main(RunTest.java:8)

As a stopgap, I removed the plug-ins and explicitly defined a dependency on io.opentelemetry:opentelemetry-api:1.36.0 which integration's TCL requires.
More investigation is needed to clean these dependencies up.