Upgrade TCL to 1.0.9
./gradlew service:bootRun was failing out of the gate with java.lang.NoClassDefFoundError: io/opentelemetry/instrumentation/api/internal/SemconvStability
I updated dependencies using https://github.com/DataBiosphere/terra-common-lib/pull/131 as a guide (which is included in this TCL version bump).
Is there a way to inherit these OTEL dependencies from TCL?